# Recommended location for database
db_file            "~/.config/mpd/database"

# Listen on Unix domain socket
bind_to_address "$XDG_RUNTIME_DIR/mpd/socket"

# Uncomment to refresh the database whenever files in the music_directory are changed
music_directory    "~/Music"

# Uncomment to refresh the database whenever files in the music_directory are changed
auto_update "yes"

# Uncomment to enable the functionalities
#playlist_directory "~/.config/mpd/playlists"
#pid_file           "~/.config/mpd/pid"
#state_file         "~/.local/state/mpd/state"
#sticker_file       "~/.config/mpd/sticker.sql"

# Audio shit
audio_output {
    type            "alsa"
        name            "My ALSA Device"
}

